{% set name = "rpcq" %}
{% set version = "2.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 536fbe1ed6551300990a75bc0fd66a2dc25a31d7f3bd04d79de5c9357e066b87

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - python  >=3.6.0
    - pip
  run:
    - python
    - future
    - msgpack-python  >=0.5.2
    - python-rapidjson
    - pyzmq  >=17
    - ruamel.yaml
    - typing

test:
  imports:
    - rpcq

about:
  home: https://www.rigetti.com
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'The RPC framework and message specification for Rigetti QCS'
  dev_url: https://github.com/rigetticomputing/rpcq

extra:
  recipe-maintainers:
    - karalekas
